# Generated by Django 5.1.6 on 2026-01-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('overview', models.TextField()),
                ('skills', models.TextField(help_text='Required skills for this career')),
                ('education_path', models.TextField(help_text='Educational requirements and path')),
                ('institutions', models.TextField(help_text='Recommended institutions')),
                ('future_prospects', models.TextField(help_text='Future career prospects')),
                ('image', models.ImageField(blank=True, null=True, upload_to='careers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
