# Generated by Django 5.1.6 on 2026-01-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerDiscoveryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('category', models.CharField(choices=[('interests', 'Interests'), ('skills', 'Skills & Abilities'), ('personality', 'Personality'), ('subjects', 'Favorite Subjects')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='career',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers', to='careers.careercategory'),
        ),
        migrations.CreateModel(
            name='CareerProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('subjects_required', models.TextField(blank=True)),
                ('skills_to_develop', models.TextField(blank=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='careers.career')),
            ],
        ),
        migrations.CreateModel(
            name='CareerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('explanation', models.CharField(blank=True, max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='careers.careerquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CareerOptionWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_weights', to='careers.career')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_weights', to='careers.careeroption')),
            ],
            options={
                'unique_together': {('option', 'career')},
            },
        ),
        migrations.CreateModel(
            name='CareerDiscoveryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='careers.careerdiscoveryresponse')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careerquestion')),
            ],
            options={
                'unique_together': {('response', 'question')},
            },
        ),
    ]
