# Generated by Django 5.1.6 on 2026-01-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careercategory_careerdiscoveryresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerprogram',
            name='country',
            field=models.CharField(default='Rwanda', max_length=100),
        ),
        migrations.AddField(
            model_name='careerprogram',
            name='institution_type',
            field=models.CharField(choices=[('school', 'School'), ('university', 'University')], default='university', max_length=20),
        ),
        migrations.AddField(
            model_name='careerprogram',
            name='level',
            field=models.CharField(choices=[('ordinary', 'Ordinary Level (S1-S3)'), ('advanced', 'Advanced Level (S4-S6)')], default='advanced', max_length=20),
        ),
    ]
