# Generated by Django 5.1.6 on 2026-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_careerprogram_country_careerprogram_institution_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='riasec_primary',
            field=models.CharField(blank=True, choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=1),
        ),
        migrations.AddField(
            model_name='career',
            name='riasec_secondary',
            field=models.CharField(blank=True, help_text='Comma-separated secondary RIASEC codes, e.g. I,A', max_length=10),
        ),
        migrations.AddField(
            model_name='careeroption',
            name='value',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='careerquestion',
            name='category',
            field=models.CharField(choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=20),
        ),
    ]
