# Generated by Django 5.1.6 on 2026-02-18 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_career_riasec_primary_career_riasec_secondary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('description', models.TextField()),
                ('suggested_careers', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='careercategory',
            name='code',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.CreateModel(
            name='CareerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_started'],
            },
        ),
        migrations.CreateModel(
            name='CareerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realistic_score', models.PositiveIntegerField(default=0)),
                ('investigative_score', models.PositiveIntegerField(default=0)),
                ('artistic_score', models.PositiveIntegerField(default=0)),
                ('social_score', models.PositiveIntegerField(default=0)),
                ('enterprising_score', models.PositiveIntegerField(default=0)),
                ('conventional_score', models.PositiveIntegerField(default=0)),
                ('primary_code', models.CharField(max_length=1)),
                ('secondary_code', models.CharField(max_length=1)),
                ('tertiary_code', models.CharField(max_length=1)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='careers.careerassessment')),
            ],
        ),
        migrations.CreateModel(
            name='CareerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careerquestion')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='careers.careerassessment')),
            ],
            options={
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
