# Generated by Django 5.1.6 on 2026-01-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careercategory_careerdiscoveryresponse_and_more'),
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='career_categories',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='careers.careercategory'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='career_focuses',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='careers.career'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='student_levels',
            field=models.CharField(blank=True, help_text='Comma-separated: O-Level, A-Level', max_length=50),
        ),
    ]
