# Generated by Django 5.1.6 on 2026-01-19 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='partner',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['mentor', 'partner']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
