# Generated by Django 5.1.6 on 2026-02-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_question_coursechapter_chaptercontent_choice_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
